#pragma once

enum INSP_RESULT_ID
{
	INSP_PASS=0,
	INSP_FAIL_BALL_HEIGHT,
	INSP_FAIL_BALL_COPLAN,
	INSP_FAIL_BALL_PITCH,
	INSP_FAIL_BALL_QUALITY,
	INSP_FAIL_WARPAGE,
	INSP_FAIL_PAD_SIZE,
	INSP_FAIL_MATRIX_CODE,
	INSP_FAIL_PVI_DEFECT1
};